name          'puppet-sabnzbd'
version       '0.0.1'
source        'https://github.com/DexterTheDragon/puppet-sabnzbd'
author        'DexterTheDragon'
license       'Apache License, Version 2.0'
summary       'Module for installing sabnzbd+'
description   'Installs sabnzbd+'
project_page  'https://github.com/DexterTheDragon/puppet-sabnzbd'

dependency 'puppetlabs/stdlib'
